services:
  amc-monitor:
    build: .
    container_name: amc-showtime-monitor
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      TZ: America/Los_Angeles
      PORT: 8080
      CONFIG_PATH: /data/config.json
      DATABASE_PATH: /data/amc-monitor.db
    ports:
      - '8080:8080'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
